# 爬虫
crawler:
  # github的cookie
  TopicHeaders:
    Cookie: '_octo=GH1.1.547050398.1730121222; _device_id=73a715dea9188e9052280e9ba8f00a3d; saved_user_sessions=124904356%3AFGDwEe-yLWPAB9iCFsxyTgm-Ij8frauGVZNDils0DyQ_FDi4; user_session=FGDwEe-yLWPAB9iCFsxyTgm-Ij8frauGVZNDils0DyQ_FDi4; __Host-user_session_same_site=FGDwEe-yLWPAB9iCFsxyTgm-Ij8frauGVZNDils0DyQ_FDi4; logged_in=yes; dotcom_user=yizhilsy; color_mode=%7B%22color_mode%22%3A%22auto%22%2C%22light_theme%22%3A%7B%22name%22%3A%22light%22%2C%22color_mode%22%3A%22light%22%7D%2C%22dark_theme%22%3A%7B%22name%22%3A%22dark%22%2C%22color_mode%22%3A%22dark%22%7D%7D; preferred_color_mode=light; tz=Asia%2FShanghai; _gh_sess=wgcGGu1teQcioqHPiWBCx0tVV%2BgI4OSl5S1WSmwI4%2BLlrg7DS2GFaw1Z%2BTJRYq4SKGHp%2Fm4b9ZkIfhQqgACyapyAa8XZtdkOIGF%2Fkk%2BTwIj9ibdWec5%2B8oofaPsQipgRe7Jmfv3LPdqazTY%2BxAj8IujwSpfd%2BSaJqI3QPiZucUbs%2FYPRwWQfcz7qWrb0%2Ftzbd0eeLfAQg75s1uxusz67iprHm%2Fl0rFU6ZOrzMB1Gl4uVPDXP%2FkOwpiCLFvgWUaKEgTAEy2C4T%2BMTFL285JZ1cDY1rM0TPhOkU89zIezfnw6YflOnC%2FE%2FhgRne3QOWKI1mAvd%2BleJNC3EE0nVhVZwC5I%2FQw0%2BuJGikotXbvSc0MWRrHsaD1Nen3gR6WAchiW6--2m9XRat%2B2oaDceNY--FmGSxVluLBuvzl1Y7CQe5A%3D%3D'
    Sec-Ch-Ua-Platform: '"Windows"'
    X-Requested-With: 'XMLHttpRequest'
    Accept-Language: 'zh-CN,zh;q=0.9'
    Accept: 'text/html'
    Sec-Ch-Ua: '"Not?A_Brand";v="99", "Chromium";v="130"'
    User-Agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.6723.59 Safari/537.36'
    Sec-Ch-Ua-Mobile: '?0'
    Sec-Fetch-Site: 'same-origin'
    Sec-Fetch-Mode: 'cors'
    Sec-Fetch-Dest: 'empty'
    Referer: 'https://github.com/topics'
    Accept-Encoding: 'gzip, deflate, br'
  RepoHeaders:
    User-Agent: 'Mozilla/5.0'
    Authorization: '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'
    Content-Type: 'application/json'
    Accept: 'application/vnd.github.text-match+json'
doubaoAPI:
  Headers:
    User-Agent: 'Mozilla/5.0'
    Authorization: 'dc7fa403-c593-44f7-99e8-ff9e6195c26b'
    Content-Type: 'application/json'
  Body:
    model: 'ep-20241101174100-6hfvz'
    messages:
      role1: 'system'
      content1: 'This string is the search string submitted by the user. Please classify this string as the specified topic for you, which can be classified as multiple topics.here are the specified topic arrays: [3d, ajax, algorithm, amphp, android, angular, ansible, api, arduino, aspnet, awesome, aws, azure, babel, bash, bitcoin, bootstrap, bot, c, chrome, chrome-extension, cli, clojure, code-quality, code-review, compiler, continuous-integration, cpp, cryptocurrency, crystal, csharp, css, data-structures, data-visualization, database, deep-learning, dependency-management, deployment, django, docker, documentation, dotnet, electron, elixir, emacs, ember, emoji, emulator, eslint, ethereum, express, firebase, firefox, flask, font, framework, frontend, game-engine, git, github-api, go, google, gradle, graphql, gulp, hacktoberfest, haskell, homebrew, homebridge, html, http, icon-font, ios, ipfs, java, javascript, jekyll, jquery, json, julia, jupyter-notebook, koa, kotlin, kubernetes, laravel, latex, library, linux, localization, lua, machine-learning, macos, markdown, mastodon, material-design, matlab, maven, minecraft, mobile, monero, mongodb, mongoose, monitoring, mvvmcross, mysql, nativescript, nim, nlp, nodejs, nosql, npm, objective-c, opengl, operating-system, p2p, package-manager, parsing, perl, phaser, php, pico-8, pixel-art, postgresql, project-management, publishing, pwa, python, qt, r, rails, raspberry-pi, ratchet, react, react-native, reactiveui, redux, rest-api, ruby, rust, sass, scala, scikit-learn, sdn, security, server, serverless, shell, sketch, spacevim, spring-boot, sql, storybook, support, swift, symfony, telegram, tensorflow, terminal, terraform, testing, twitter, typescript, ubuntu, unity, unreal-engine, vagrant]'
      role2: 'user'

