// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calc.proto

// Protobuf Java Version: 3.25.5
package com.calc.proto;

public interface CalcReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculator.CalcReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 a = 1;</code>
   * @return The a.
   */
  int getA();

  /**
   * <code>int32 b = 2;</code>
   * @return The b.
   */
  int getB();
}
