// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calc.proto

// Protobuf Java Version: 3.25.5
package com.calc.proto;

public interface CalcRspOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculator.CalcRsp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 result = 1;</code>
   * @return The result.
   */
  int getResult();
}
